# Generated by Django 6.1.1 on 2026-09-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_code', models.CharField(max_length=64, unique=True)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('task', 'Task')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('details', models.TextField()),
                ('completed', models.BooleanField(blank=True, null=True)),
                ('legacy_author', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='crm.company')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='opportunities.opportunity')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'occurred_at'], name='activities__company_944da7_idx'), models.Index(fields=['opportunity', 'occurred_at'], name='activities__opportu_d84ea3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_on', models.DateField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='opportunities.opportunity')),
            ],
            options={
                'indexes': [models.Index(fields=['due_on', 'completed_at'], name='activities__due_on_1e42a0_idx')],
            },
        ),
    ]
