# Generated by Django 6.1.1 on 2026-09-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=16),
        ),
    ]
