# Generated by Django 6.1.1 on 2026-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, unique=True)),
                ('source_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
