# Generated by Django 6.1.1 on 2026-09-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='file_counts',
            field=models.JSONField(default=dict),
        ),
    ]
