# Generated by Django 6.1.1 on 2026-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FairEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_code', models.CharField(max_length=64, unique=True)),
                ('fair_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('venue', models.CharField(max_length=255)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('max_stand_height_m', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'indexes': [models.Index(fields=['fair_name', 'starts_on'], name='fairs_faire_fair_na_eb7e2f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='fair_edition_end_not_before_start'), models.CheckConstraint(condition=models.Q(('max_stand_height_m__gte', 0)), name='fair_edition_height_non_negative')],
            },
        ),
    ]
