# Generated by Django 6.1.1 on 2026-09-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fairedition',
            name='fair_edition_height_non_negative',
        ),
        migrations.AlterField(
            model_name='fairedition',
            name='max_stand_height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='fairedition',
            constraint=models.CheckConstraint(condition=models.Q(('max_stand_height_m__isnull', True), ('max_stand_height_m__gte', 0), _connector='OR'), name='fair_edition_height_non_negative'),
        ),
    ]
