# Generated by Django 6.1.1 on 2026-09-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('province_code', models.CharField(blank=True, max_length=16)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('sales_rep', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='crm_company_name_895a0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_code', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('fax', models.CharField(blank=True, max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='crm.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'last_name', 'first_name'], name='crm_contact_company_8da3c0_idx')],
            },
        ),
    ]
