# Generated by Django 6.1.1 on 2026-09-15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_search_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                django.db.models.functions.text.Upper("legacy_code"),
                name="company_legacy_upper_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                django.db.models.functions.text.Upper("legacy_code"),
                name="contact_legacy_upper_idx",
            ),
        ),
    ]
