# Generated by Django 6.1.1 on 2026-09-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('fairs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('amount_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_stage', models.CharField(choices=[('open', 'Open'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=16)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('expected_close_on', models.DateField(blank=True, null=True)),
                ('historical_campaign_code', models.CharField(blank=True, max_length=128)),
                ('stand_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client_budget_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requested_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('brief_notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.company')),
                ('fair_edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='fairs.fairedition')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_opportunities', to='crm.contact')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'fair_edition'], name='opportuniti_company_0f4eda_idx'), models.Index(fields=['sales_stage', 'expected_close_on'], name='opportuniti_sales_s_1ad69a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_eur__isnull', True), ('amount_eur__gte', 0), _connector='OR'), name='opportunity_amount_non_negative'), models.CheckConstraint(condition=models.Q(('stand_area_sqm__isnull', True), ('stand_area_sqm__gte', 0), _connector='OR'), name='opportunity_area_non_negative'), models.CheckConstraint(condition=models.Q(('client_budget_eur__isnull', True), ('client_budget_eur__gte', 0), _connector='OR'), name='opportunity_budget_non_negative'), models.CheckConstraint(condition=models.Q(('requested_height_m__isnull', True), ('requested_height_m__gte', 0), _connector='OR'), name='opportunity_height_non_negative')],
            },
        ),
    ]
