# Generated by Django 6.1.1 on 2026-09-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='raw_legacy_status',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
