# Generated by Django 6.1.1 on 2026-09-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('preparer_output', models.TextField(blank=True)),
                ('reviewer_output', models.TextField(blank=True)),
                ('decision', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('policy_version', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('technical_readiness', models.CharField(choices=[('not_requested', 'Not requested'), ('early_intake', 'Early intake'), ('blocked', 'Blocked'), ('ready', 'Ready')], default='not_requested', max_length=32)),
                ('error_type', models.CharField(blank=True, max_length=128, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoff_runs', to='opportunities.opportunity')),
            ],
            options={
                'indexes': [models.Index(fields=['opportunity', 'created_at'], name='handoffs_ha_opportu_12433b_idx')],
            },
        ),
    ]
